sudo: false

language: python

python:
  - 3.7
  - 3.8

install:
  - pip install coveralls
  - pipenv install

script:
  - coverage run --source=mirage_test setup.py test

after_success:
  - coveralls
